### ISSUE TITLE
Portuguese translation and problem with PDF merge

### ISSUE THREAD

**Issue by PieBonds** [scoute-dich/PDFCreator#23] opened 2017-06-07 13:09 UTC
Hi, I'm here to ask two things. One is if you'd like me to translate the app to Portuguese, as I'm native on the language, and if the problem when merging PDFs only occurs with me. The app instantly stops working when I tap the merge icon under "+text".
Thanks for your wonderful job on the app.

**Comment by scoute-dich** [comment] 2017-06-11 09:48
Hi,

sorry for late response, but I was on vacation. I can't reproduce the force close when choosing merge pdf... Which Android version are you using? I assume, that you gave the app the permission to read/write storage?

About translation in Portuguese:

I just created two files in the "res/values-pt" folder:

- dialogs.xml
- strings.xml

If you want to translate it, I would be very glad.

Thanks for your interest in my app.

Regards
Gaukler Faun

**Comment by scoute-dich** [comment] 2017-06-14 14:35
Which Android Version are you using? Is it possible that you didn't grant permission to read and write files on Sdcard, if you use Marshmallow+?

**Comment by scoute-dich** [comment] 2017-06-25 12:34
Is the problem still there (merging pdf). Because with latest release I changed some permission dialogs. Perhaps that was the problem...

**Comment by scoute-dich** [comment] 2017-08-09 06:28
Since there is no answer, I'll close the issue. Feel free to open again of there are further problems.

_Gesendet von meinem Oneplus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Closed** 2017-08-09 06:28 UTC
