### ISSUE TITLE
Crash when open PDF

### ISSUE THREAD

**Issue by AlphaOmega3** [scoute-dich/PDFCreator#7] opened 2016-10-25 17:26 UTC
when I try to open a PDF app is not among those available to perform the action;

if, instead, I try to select a PDF from within the app, the app crashes .. solutions?

**Comment by scoute-dich** [comment] 2016-10-26 08:34
PDF-Creator is not a PDf-viewer, so it is normal that the app is not available for that action...

The second point I do not understand...

Where do you try to select a pdf (which tab, which button)?

**Comment by scoute-dich** [comment] 2016-10-26 08:36
PDF-Creator is not a PDf-viewer, so it is normal that the app is not available for that action...

The second point I do not understand...

Where do you try to select a pdf (which tab, which button)?

**Comment by AlphaOmega3** [comment] 2016-10-26 09:13
in both ways..

**Comment by scoute-dich** [comment] 2016-11-01 12:35
Can you please explain exactly, what buttons you press in which app? I can not reproduce this bug. Here everything works fine. Which Android version are you using? Can produce a logcat?

**Comment by AlphaOmega3** [comment] 2016-11-02 21:21
I use Android 5.1.1 - I can't use logcat 

1) I open the app 
2) I open the menu 
3) select "open app folder" 
4) the app crashes and tell me "PDF file not found or corrupted"
5) the app restart

**Comment by scoute-dich** [comment] 2016-11-05 07:41
That's strange because this should open the file explorer not the pdf reader. Of you don't have a file explorer installed there should come a warning message.

**Comment by AlphaOmega3** [comment] 2016-11-05 10:51
I have 2 file manager (OI file manager and ZArchiver) + 1 PDF viewer (Document Viewer)

**Comment by scoute-dich** [comment] 2016-11-05 21:43
Now I can confirm the bug. I will look on it in the next days.

**Comment by scoute-dich** [comment] 2016-11-05 21:44
Which Android version are you using?

**Comment by AlphaOmega3** [comment] 2016-11-05 22:34
I use Android 5.1.1 on SM-N7505

**Comment by scoute-dich** [comment] 2016-11-06 12:59
Can you test, if the bug is solved with attached zip compressed apk? On my device
[app-release.apk.zip](https://github.com/scoute-dich/PDFCreator/files/573832/app-release.apk.zip)
 it is working.

**Comment by AlphaOmega3** [comment] 2016-11-06 13:47
installed and started .. but gives me the same error before. at this point could be my phone and not the app. anyway thank you for the time and availability

**Comment by scoute-dich** [comment] 2016-11-06 15:13
Ok. Then I will close the issue.

**Closed** 2016-11-06 16:07 UTC
Labels: question
